<?php
    $collection = $block->getCatFaqCollection();
?>
<div class="link2Back">
    <button>
        <a href="<?=$block->escapeUrl($block->getUrl('faq'))?>">
            <?=$block->escapeHtmlAttr(__('Back to Faq'))?>
        </a>
    </button>
</div>
<div class="detail_page">
    
    <div class="acc-container">
        <?php foreach ($collection as $key => $data): ?>
            <div class="acc">
                <div class="acc-head">
                    <p><?=$block->escapeHtmlAttr($data->getQuestion());?></p>
                </div>
                <div class="acc-content">
                    <p><?= /* @noEscape */ $data->getAnswer();?></p>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Bluethink_Faq/js/faqjs": {}
        }
    }
</script>